server:
  port: 8761  # Default port for Eureka Server

eureka:
  client:
    register-with-eureka: false  # Eureka server does not register with itself
    fetch-registry: false
  server:
    enable-self-preservation: false  # Optional for dev purposes
